### PR TITLE
CanvasRenderingContext2D class implementation

### PR DESCRIPTION
**Pull request by jtenner**
This pull request is to keep track of development on the `CanvasRenderingContext2D` class.

# Goals

1. Implement the props and verify input values on *all* properties
1. Implement `save()` and `restore()` stack values
1. Add Support for `DOMMatrix` (used in `currentTransform` and `getTransform()`)
1. Add Support for `ImageData` (used in `getImageData` and `putImageData`)
1. Create test file for each property and each function

# Checklist

## Aims

- [x] Achieve 100% test coverage
- [x] Emulate stacked save/restores properly
- [x] Create test file for each property and function
- [x] Implement DOMMatrix
- [x] Test DOMMatrix
- [x] Implement ImageData
- [x] Test ImageData
## Properties

- [x] canvas
- [x] currentTransform
- [x] direction
- [x] fillStyle
- [x] filter (partial implementation because I cannot find a good css filter parser)
- [x] font
- [x] globalAlpha
- [x] globalCompositeOperation
- [x] imageSmoothingEnabled
- [x] imageSmoothingQuality
- [x] lineCap
- [x] lineDashOffset
- [x] lineJoin
- [x] lineWidth
- [x] miterLimit
- [x] shadowBlur
- [x] shadowColor
- [x] shadowOffsetX
- [x] shadowOffsetY
- [x] strokeStyle
- [x] textAlign
- [x] textBaseline

## Methods

- [x] addHitRegion()
- [x] arc()
- [x] arcTo()
- [x] beginPath()
- [x] bezierCurveTo()
- [x] clearHitRegions()
- [x] clearRect()
- [x] clip()
- [x] closePath()
- [x] createImageData()
- [x] createLinearGradient()
- [x] createPattern()
- [x] createRadialGradient()
- [x] drawFocusIfNeeded()
- [x] drawImage()
- [x] ellipse()
- [x] fill()
- [x] fillRect()
- [x] fillText()
- [x] getImageData()
- [x] getLineDash()
- [x] getTransform()
- [x] isPointInPath()
- [x] isPointInStroke()
- [x] lineTo()
- [x] measureText()
- [x] moveTo()
- [x] putImageData()
- [x] quadraticCurveTo()
- [x] rect()
- [x] removeHitRegion()
- [x] resetTransform()
- [x] restore()
- [x] rotate()
- [x] save()
- [x] scale()
- [x] scrollPathIntoView()
- [x] setLineDash()
- [x] setTransform()
- [x] stroke()
- [x] strokeRect()
- [x] strokeText()
- [x] transform()
- [x] translate()

# Current Test Coverage
```
-----------------------------|----------|----------|----------|----------|-------------------|
File                         |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-----------------------------|----------|----------|----------|----------|-------------------|
All files                    |      100 |      100 |      100 |      100 |                   |
 CanvasGradient.js           |      100 |      100 |      100 |      100 |                   |
 CanvasPattern.js            |      100 |      100 |      100 |      100 |                   |
 CanvasRenderingContext2D.js |      100 |      100 |      100 |      100 |                   |
 DOMMatrix.js                |      100 |      100 |      100 |      100 |                   |
 ImageData.js                |      100 |      100 |      100 |      100 |                   |
 Path2D.js                   |      100 |      100 |      100 |      100 |                   |
 TextMetrics.js              |      100 |      100 |      100 |      100 |                   |
-----------------------------|----------|----------|----------|----------|-------------------|
```

### CODE REVIEW

**Comment by jtenner** [comment]
Feel free to interject any comments you have. I've been working on this prototype for the past five years. and I have a lot of experience with this.

**Comment by jtenner** [comment]
@hustcc Hey this is completed! Feel free to take a look and make sure it fits your standards.

**Comment by hustcc** [comment]
👍 Really nice work!

**Comment by hustcc** [comment]
Impeccable!

 - `var` -> `const / let`.
 - maybe need a overall test with a canvas library. Can be fill after pr merged. 

Is there a willingness to be a maintainer?

**Comment by jtenner** [comment]
I want to make sure I'm following the specification, so please check the pr! Other than that, I would love to help out maintaining this library. I need to contact you about the upgrade to jest 24, because there are some problems with it. Is there a special way to get wechat to work?

**Comment by jtenner** [comment]
(also, I should probably implement toBlob())

**Comment by jtenner** [comment]
@AdriaRios I believe #20 will supercede this pull request. After talking with @hustcc , he seemed to think upgrading to jest24 and babel7 would be fine.

**Comment by AdriaRios** [comment]
Ok! Could be great to add toBlob in this PR then

**Pull request merged**
