### PR TITLE
fix(jest-canvas-mock): account for possible `TypeError`

### LINKED ISSUE #115: new `mockPrototype(win)` implementation can cause `TypeError`
I am running into an issue when upgrading to [`2.5.1`](https://renovatebot.com/diffs/npm/jest-canvas-mock/2.5.0/2.5.1) and I believe it has something to due with changes in #100.

```log
...
client:test: TypeError: Cannot read properties of undefined (reading 'prototype')
client:test:  ❯ mockPrototype ../../node_modules/.pnpm/jest-canvas-mock@2.5.1/node_modules/jest-canvas-mock/lib/mock/prototype.js:37:50
client:test:  ❯ Proxy._default ../../node_modules/.pnpm/jest-canvas-mock@2.5.1/node_modules/jest-canvas-mock/lib/window.js:61:26
client:test:  ❯ src/setupTests.ts:31:22
client:test:      [29](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:30)| ] as const;
client:test:      [30](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:31)| 
client:test:      [31](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:32)| const canvasWindow = getCanvasWindow({ document: window.document });
client:test:        |                      ^
client:test:      [32](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:33)| 
client:test:      [33](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:34)| apis.forEach((api) => {
...
```

looking at [the test case](https://github.com/hustcc/jest-canvas-mock/blob/master/__tests__/mock/window.js), it only covers when there is a wellformed window object.

Not sure what the expected behavior when something other than a wellformed window object is; however I was not seeing the above error in `2.5.0` and below. There seems to some delta between the global objects (`HTMLCanvasElement`, etc.) and this newly passed window object.

currently failing line: https://github.com/hustcc/jest-canvas-mock/blob/master/src/mock/prototype.js#L37

```js
...
  win.HTMLCanvasElement.prototype.getContext = getContext2D;
...
```

---

## suggestion

_suggestion_ - update the code to have this change be more conditional where we check if the passed in `win` object has the necessary props to not error in functions like `getContext2D`, and if it does not; fall back to the old behavior ( `mockPrototype()` ).

drawbacks, this potentially might be masking something in a project where the user expects the browser to behave one way; and due to all this mocking abstraction it behaves differently during testing. I think this is acceptable since, we are already basically doing this now, it just will behave slightly differently with the proposed suggestion than it does now, so I wanted to call it out.

_Originally posted by @virtuoushub in https://github.com/hustcc/jest-canvas-mock/issues/100#issuecomment-1564406609_

### PR DESCRIPTION
**Pull request by virtuoushub**
closes #115

### CODE REVIEW

**Review by hustcc — APPROVED** [review]

**Comment by hustcc** [comment]
@virtuoushub hello, help to update the version? thanks.

**Comment by virtuoushub** [comment]
> #115

Hi @hustcc, is the ask if this should be a patch/minor/major? I think just a patch as it fixes a bug.

---

If the ask is for a summary of these changes, #115 has all the details surrounding the bug these changes attempt to fix.

The gist of the changes in this PR is that they bring back the old logic from before #100 for those cases where the `window` object is not what the test framework expects; but also allow for #100 to work as expected if the `window` object _does_ contain the expected properties.

**Comment by hustcc** [comment]
Only update package.version = 2.5.2.

**Comment by hustcc** [comment]
+ jest-canvas-mock@2.5.2

**Pull request merged**
