### PR TITLE
feat(mock): support mocks via __getPath, __getEvents, and __getDrawCalls

### LINKED ISSUE #33: Method to log commands to context and snapshot test?
Hello, I was wondering if it is possible to use this library to log the drawing commands submitted to a context and retrieve them as a list.

Thanks

### LINKED ISSUE #39: Add typescript types file to expose types for mock calls

### LINKED ISSUE #40: Readme has wrong expectation
```
    Expected name: "TypeError"                                                                                                                           
    Received name: "Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-10) is negative."                                       
                                                                                                                                                         
    Received message: "IndexSizeError"                                                                                                                   
                                                                                                                                                         
          3 |   const ctx = canvas.getContext('2d')                                                                                                      
          4 |   expect(() => ctx.arc(1, 2, 3, 4)).toThrow(TypeError);                                                                                    
        > 5 |   expect(() => ctx.arc(0, 0, -10, 0, Math.PI * 2)).toThrow(TypeError); 
```

This can be fixed before 2.1.0

### PR DESCRIPTION
**Pull request by jtenner**
This is a very large pull request that enables testing canvas context function call events via:

```ts
const events = CanvasRenderingContext2D.__getEvents(ctx);
expect(events).toMatchSnapshot();
```

Please see the following test files to see how to use this feature:

```
__tests__\classes\CanvasRenderingContext2D.__getDrawCalls.js
__tests__\classes\CanvasRenderingContext2D.__getPath.js
__tests__\classes\CanvasRenderingContext2D.__getEvents.js
```

closes #33 
closes #39 
closes #40

### CODE REVIEW

**Comment by jtenner** [comment]
This pull request is big enough, @hustcc should probably check my work before it's pulled.

**Comment by hustcc** [comment]
@jtenner nice work, If the pr is ready, you can just merge it by yourself. 😄

**Comment by jtenner** [comment]
Definitely. I'll do this tomorrow.

**Comment by jtenner** [comment]
I actually need to check that the d.ts file works as intended.

**Comment by jtenner** [comment]
@hustcc We can release 2.1.0 now. Thanks!

**Pull request merged**
