### PR TITLE
Added canvas as a property to the context2d.

### PR DESCRIPTION
**Pull request by stijndepestel**
Hi,

For a test, we were using a library which uses the canvas property on the context object to retrieve the canvas. According to the specs of the canvas API, this property has to be defined as well. Hence I have added it to the context object.

Any comments are appreciated.

Kind Regards,

### CODE REVIEW

**Comment by hustcc** [comment]
Thank you for your pr. But write like above, maybe better ?

```js
// ...

const createContext2d = jest.fn((type, canvas) => {
  const ctx = jestWrapper(context2d);
  ctx.canvas = canvas;
});

export default createContext2d;
```

**Comment by stijndepestel** [comment]
I've updated accordingly and added a test to verify the canvas property exists.

**Comment by stijndepestel** [comment]
Thanks! When will you be releasing this? Then I can update my dependencies accordingly.

**Comment by hustcc** [comment]
v0.0.4 release.

And add a feature, make context2d immutable.

**Pull request merged**
