### PR TITLE
fix error desc, add two generic tests

### PR DESCRIPTION
**Pull request by jtenner**
This pull request aims to clean up the error descriptions, and verify error types. It also comes with a few generic tests that should have been added to begin with.

- [x] Verify Error Descriptions
- [x] Verify Error Parameters (e.g. DOMException)
- [x] Add CanvasGradient tests and conform to HTML Standard specification

### CODE REVIEW

**Comment by hustcc** [comment]
Has any other commit?

**Comment by jtenner** [comment]
I am sorry for not being active on this project. I found myself unable to work on this for a while because of a death in the family. I need a bit more time to complete this.

**Comment by jtenner** [comment]
I've been giving this commit a lot of thought, and could use your input on this. Any thoughts?

**Comment by jtenner** [comment]
@hustcc

**Comment by hustcc** [comment]
Here, busy these days. I have not other thought, I think stable version should be released.

**Comment by jtenner** [comment]
Lgtm! I promise to help on any future errors if something goes wrong. Ty for feedback.

**Comment by hustcc** [comment]
help to add a changeLog, you can push to master directly.

**Pull request merged**
